language: node_js
sudo: required
dist: trusty
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created via the "travis encrypt" command using the project repos public key
    - secure: "OiwX40Ex/EiNhHEyk7X+CxqO1oKg/3Ct3A7jZ1/dRAU7wtkPltMXGFVcjC1fDgCKNbJWaq4GLRpTXHgz1Eoc+qed0cAOuIGf4PZepZTFRyHVPCkjvqTz/AsTIwvwAbROPKWobE2dcoTHFH40E0EpqNMQvuLcRg3M0+m1g3p8h4f7E0W6fU7rc1vAcsyb8yiLvu3/OX/5+TXjl6j88pKMHNo5RmKclXTQCC8r2WTyewilR1NpRNBc205eiqukO/sQ74803frwZTlY57fyogpAa7Ot4BS3eAAnjbGHD3Ov/6vZiaHAN1JyreD+rXbXpzxGaOxy/f4xLQHkv9Cq7wE5zFsQfvojV4ucmWQBV3wq0u6YG9z9fWWakzpC9XcU6slGnbj2Pt92+hzsyukIzclA+yNh32UsqQs/yx/dkxBrHFtKr8muPJju8CaQnUNg6GfDRkxjrW+iKi7VfImDfFHbfVu0CdgFjA8fnrJj7oP61GknhF7+/lXRnEu5YATGpVTIYkfW70ccr0/aqWUw5PCSQxlkEksxjAqgpC9WIXpPMSmAOJR+h5nNyKcubAwi+Jf2OGVFo/osW6FG4/chxPYSoq88IwSlgt40RLWL0M5SFv7NI/sV2CEF17OLQrZYRqtG0SlbOJdj7BX3U/LbNTkheJEXBDzIulviqjGzUUvRoPU="
before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: "Teradata/covalent-code-editor"
      description: "Text and code editing based on Covalent and Monaco Editor"
    notification_email: jeremy.smartt@teradata.com
    build_command_prepend: "npm run build"
    build_command: "--no-command --fs-capture-search dist/"
    branch_pattern: coverity_scan
node_js:
- '10.15.3'
branches:
  only:
    - coverity_scan
jobs:
  include:
    - env: "MODE=coverity"
install:
- npm install
script:
- ./scripts/ci/travis-script.sh
cache:
  directories:
    - ./node_modules/
